### ISSUE TITLE
Add mixed_cutoff paramter to `thermo.depth` and `meta.depths` functions

### ISSUE THREAD

**Issue by jabrent** [GLEON/rLakeAnalyzer#52]
I've been trying to calculate the meta depths for a time series of water temp data from Lake Bure in Denmark that Peter Staehr works on. It's a shallow, (max. depth = 10.8 m) eutrophic lake and doesn't have strong thermal stratification. If the lake is isothermal or doesn't have a clear thermocline, I get some strange estimates. Example data and LA output:

wtr data for depths 0.5-9 m:
Bure_md = ts.meta.depths(Bure_wtr_midnight, slope=0.3, na.rm=TRUE)

7.03 7.03 7.02 7.01 7.02 7.02 7.03 7.02 7.03 7.03 ->  1.998431354 (LA top output - same for bottom)
6.86	6.86	6.87	6.86	6.86	6.86	6.87	6.87	6.87	6.87 ->  2.666667667 

Luke's original comment:
It will always try to give you a thermocline depth, even if, really, there isn't one (for example, supply it repeating values, like rep(4, 10))

>  thermo.depth(rep(9,10), c(0.5,1:9), Smin=2) 
[1] 0.75

There is no cutoff for the thermocline and if the cutoff eliminates the seasonal thermocline, it will still default to returning the non-seasonal thermocline depth.
 
- - -

Any suggestion for improving the estimate? My understanding is that if the water column is not stratified, the function is supposed to return the max. depth, which would be helpful. I'm mostly concerned with calculating the mixed layer depth (meta top) and using a larger cut-off (slope =0.3) to avoid temporary near-surface stratification.

**Comment by lawinslow** [comment]
Ok, I verified this is the same behavior as the original LA. 

> depths =
>     1     2     3     4     5     6     7     8     9    10
> ans =
>  Columns 1 through 6
>  999.8092  999.8092  999.8092  999.8092  999.8092  999.8092
>  Columns 7 through 10
>  999.8092  999.8092  999.8092  999.8092
> FindThermoDepth(dens, depths, 0.1)
> ans =
>   1.5000

This may not have been an issue in LA-matlab due to the other processing that was happening (averaging and such). 

- - -

**What is the desired behavior?**

1. At the very least, the algorithm should output NA or bottom depth for an isothermal profile. 

2. A density gradient cutoff could be supplied to set a lower limit for what we would call "thermocline". Smin is only applied for the seasonal thermocline. (this could default to zero to keep default behavior consistent)

3. Hmmmm.

**Comment by jread-usgs** [comment]
I don't think that happens in LA matlab because of the `0.5		#mixed temp differential (∞C)` param, unless using the base functions.

**Comment by lawinslow** [comment]
Yeah, we could add something like that given that in R, the base functions are likely to be the use-case. So in that case, both thermo.depth and meta.depths could have a "mixed_cutoff" parameter. Thoughts?

**Comment by jread-usgs** [comment]
I think that makes sense, and it could default to 1.0°C, which is more common than others in the literature.

**Comment by jabrent** [comment]
Thanks for looking into this. Just to make sure I understand what you're saying if the mixed_cutoff parameter was added and the temp. differential was less than 1°C (or whatever it was set to), the output would default to NA or the max. depth?

**Comment by lawinslow** [comment]
Yup, exactly.

**Comment by lawinslow** [comment]
@jabrent I'm going to leave this open until you have tested this out with your data.

**Comment by jabrent** [comment]
ok sounds good — I'll try this out soon
