### ISSUE TITLE
Internal energy units?

### ISSUE THREAD

**Issue by lawinslow** [GLEON/rLakeAnalyzer#61]
@jread-usgs are units on internal energy actually joules/m^2 because of [this normalization](https://github.com/GLEON/rLakeAnalyzer/blob/master/R/internal.energy.R#L85)? If so, I think [the documentation](https://github.com/GLEON/rLakeAnalyzer/blob/master/R/internal.energy.R#L13) should be updated.

**Comment by jread-usgs** [comment]
sorry, I don't know why I didn't get this notice. Yes, it should be J/m2. I have changed it in the roxy block and will change the Rd file too.
