### ISSUE TITLE
confusing failure when `tempz` format is used for .wtr files

### ISSUE THREAD

**Issue by jread-usgs** [GLEON/rLakeAnalyzer#74]
Older version of rLA work with `DateTime	temp0	temp1	temp2	temp3	temp4	temp5	temp6	temp7	temp8	temp9	temp10	temp11	temp12` format (instead of `wtr_0`)

When those older files are used, they fail w/o much info:
```
Error in if (max(bthD) > depths[numD]) { : 
  missing value where TRUE/FALSE needed
```
because `depths` are all NA 

Perhaps the `get.offsets()` should error or warn if certain conditions aren't met in the input file headers?

**Comment by lawinslow** [comment]
Thanks @jread-usgs 
So, I was accidentally pushing directly to GLEON repo. I've fixed my workflow. Want to review this change? (though it is already merged...)
https://github.com/GLEON/rLakeAnalyzer/commit/54c15c2f1d34440cec2949e6fc40323823c019d2
Thanks!
