### ISSUE TITLE
Add bathy generation function?

### ISSUE THREAD

**Issue by jsta** [GLEON/rLakeAnalyzer#80]
Might be useful to include https://github.com/USGS-R/lakeattributes/blob/master/R/get_bathy.R#L25 in this package.

**Comment by lawinslow** [comment]
Ha, do you just spend days digging through the 20+ packages I have thrown out there? 

Yeah, that could probably be added. Very simple little function.

**Comment by jsta** [comment]
I think it is well written. Wish I had found if before I wrote my own equivalent but much messier function.

**Comment by jsta** [comment]
I cannot get line endings to convert to Windows using `.gitattributes` for the life of me. I am resistant to manually changing the line endings on every file modification.
