### ISSUE TITLE
Fix Vignette Titles

### ISSUE THREAD

**Issue by lawinslow** [GLEON/rLakeAnalyzer#92]
Showing up as untitled on CRAN. 
https://cran.r-project.org/package=rLakeAnalyzer

**Comment by boshek** [comment]
Fixed via: https://github.com/GLEON/rLakeAnalyzer/commit/ef6de8c3e86d24f1d4190dbb1370afeb4e3181cb

**Comment by lawinslow** [comment]
Ah, thanks. Just not on CRAN yet.
